import { describe, it, expect, vi, beforeEach } from "vitest";
import { fakeDb } from "@/lib/test-utils/fake-db";

// Coach accounts (no business_name) must behave exactly as on main after
// the clinic vertical work (src/lib/verticals/clinic). The snapshot in
// __snapshots__/coach-snapshot.test.js.snap was generated by running THIS
// file against main's code, unchanged; this branch must match it byte for
// byte. Covered: comment decisions, rendered comment templates, the AI
// reply system prompt, and the full comment pipeline's writes and sends.
//
// The file only uses APIs main already had, so it can be re-run on main to
// regenerate the snapshot. Don't update the snapshot from a feature branch:
// a diff here means coach behavior changed.

let db;
const sendPrivateReplyToComment = vi.fn(async () => ({ success: true, messageId: "mid-opener" }));
const classifyComment = vi.fn();
const sendEmail = vi.fn(async () => {});

vi.mock("@/lib/supabase/admin", () => ({ getSupabaseAdmin: () => db }));
vi.mock("@/lib/classifier", () => ({ classifyComment, CLASSIFIER_MODEL: "test", CLASSIFIER_VERSION: "test" }));
vi.mock("@/lib/contextBundle", () => ({ buildContextBundle: vi.fn(async () => ({ bundle: { id: "b1" }, offerSnapshot: null })) }));
vi.mock("@/lib/instagram", () => ({ sendPrivateReplyToComment }));
vi.mock("@/lib/token-utils", () => ({ decryptToken: () => "page-token" }));
vi.mock("@/lib/comment-to-dm-gate", () => ({ canUseCommentToDM: () => true }));
vi.mock("@/lib/comment-public-reply", () => ({ maybePostPublicReply: vi.fn(async () => {}) }));
vi.mock("@/lib/notifications", () => ({ sendEmail }));

const { decideAction, renderTemplate, DEFAULT_ACTIONS_PER_CLASS } = await import("@/lib/comment-trigger-rules");
const { buildSystemPrompt } = await import("@/lib/prompts");
const { ownerFromUser } = await import("@/lib/active-offer");
const { handleCommentEvent } = await import("./comment-event");
// main has no bookingLinkFor: there, the prompt got users.calendly_url.
const bookingLinkFor = (await import("@/lib/booking-url")).bookingLinkFor || ((u) => u?.calendly_url);

const CLASSES = Object.keys(DEFAULT_ACTIONS_PER_CLASS);
const TEMPLATES = {
  HIGH_INTENT: "hey {{COMMENTER_NAME}}! {{OFFER_NAME}} is open: {{BOOKING_LINK}}",
  ENGAGED_NOT_BUYING: "Hey! appreciate the love on {{POST_CAPTION_SNIPPET}}",
  CRITICAL_NEGATIVE: "sorry to hear that, {{COMMENTER_NAME}}",
  UNCERTAIN: "Hi there, curious what you meant? {{TREATMENT}} {{TREATMENT|x}} [first_name]",
};
const CONTEXT = { postCaption: "New cohort opens Friday, comment COACH for details on the program", commenterName: "jane", offerName: "6-Week Sprint", bookingLink: "https://calendly.com/coach/call" };
const MONITORING = [
  null,
  { enabled: true, actions_per_class: null },
  { enabled: false, actions_per_class: null },
  { enabled: true, actions_per_class: { ENGAGED_NOT_BUYING: "dm", CRITICAL_NEGATIVE: "dm", UNCERTAIN: "ignore" } },
];

describe("coach comment decisions", () => {
  it("decideAction over every class, confidence and post setting", () => {
    const out = [];
    for (const cls of CLASSES) {
      for (const confidence of [0.5, 0.79, 0.8, 0.95]) {
        for (const [m, monitoring] of MONITORING.entries()) {
          for (const templates of [TEMPLATES, {}]) {
            out.push([cls, confidence, m, templates === TEMPLATES, decideAction({ class: cls, confidence }, monitoring, templates, CONTEXT)]);
          }
        }
      }
    }
    expect(out).toMatchSnapshot();
  });
});

describe("coach rendered templates", () => {
  it("renderTemplate", () => {
    const contexts = [CONTEXT, {}, { ...CONTEXT, bookingLink: "", offerName: null, commenterName: null, postCaption: "short" }];
    expect(Object.values(TEMPLATES).flatMap((t) => contexts.map((c) => renderTemplate(t, c)))).toMatchSnapshot();
  });
});

describe("coach AI reply prompts", () => {
  const coaches = [
    { full_name: "Dom", instagram_username: "dom.coach", calendly_url: "https://calendly.com/dom/call" },
    { full_name: "Dom", instagram_username: "dom.coach", calendly_url: null },
    { full_name: "", instagram_username: "", calendly_url: "https://cal.com/x/intro" },
  ];
  const scripts = [{}, { greeting: "Hey, thanks for reaching out!", offer: "1:1 coaching", qualifying_questions: ["What's your goal?"], booking_cta: "Grab a call: {{BOOKING_LINK}}" }];
  const options = [
    {},
    { isPlayground: true },
    { conversation: { origin: "native_send" }, intentHint: "booking_cta" },
    { activeOffer: { offer_name: "Sprint", price: "$497" }, knowledge: [{ type: "faq", question: "Refunds?", answer: "14 days." }] },
  ];
  it("buildSystemPrompt with the link each path passes", () => {
    const out = [];
    for (const user of coaches) {
      for (const sc of scripts) {
        for (const opt of options) {
          out.push(buildSystemPrompt(sc, bookingLinkFor(user), { ...opt, owner: ownerFromUser(user) }));
        }
      }
    }
    expect(out).toMatchSnapshot();
  });
});

describe("coach comment pipeline end to end", () => {
  const IGBA = "17841400000000002";
  const strip = (rows) =>
    rows.map((r) =>
      Object.fromEntries(
        Object.entries(r)
          .filter(([k]) => !/(^id$|_id$|_at$)/.test(k) || ["ig_comment_id", "instagram_sender_id", "instagram_thread_id", "provider_message_id", "intent_class", "dispatched_message_id"].includes(k))
          .map(([k, v]) => [k, v])
      )
    );

  function setup({ monitoring = {}, conversations = [], webhook = false } = {}) {
    db = fakeDb(
      {
        users: [
          {
            id: "coach-1",
            email: "coach@example.com",
            instagram_business_account_id: IGBA,
            meta_page_access_token: "enc",
            comment_public_reply_enabled: false,
            plan: "unlimited",
            business_name: null,
            assistant_name: null,
            calendly_url: "https://calendly.com/coach/call",
            treatment_categories: [{ key: "strength", match: ["strength", "lifting"] }],
          },
        ],
        posts: [{ id: "p1", caption: "New cohort opens Friday, comment COACH", ig_media_id: "media-1" }],
        post_monitoring_settings: [{ creator_id: "coach-1", post_id: "p1", enabled: true, actions_per_class: null, ...monitoring }],
        comment_classifications: [],
        dm_templates: Object.entries(TEMPLATES).map(([intent_class, template]) => ({ creator_id: "coach-1", intent_class, template })),
        creator_offers: [{ creator_id: "coach-1", offer_name: "6-Week Sprint", deprecated_at: null }],
        comment_to_dm_log: [],
        conversations,
        messages: [],
        outbound_webhooks: webhook ? [{ id: "w1", user_id: "coach-1", enabled: true, event_types: ["handoff_requested", "lead_updated"] }] : [],
        outbound_webhook_events: [],
        lead_profiles: [],
      },
      { unique: { conversations: "instagram_sender_id", lead_profiles: "conversation_id" } }
    );
    db.rpc = async () => ({ data: true, error: null });
  }

  const CASES = [
    ["HIGH_INTENT", 0.95, "how much is the program? lifting focus"],
    ["HIGH_INTENT", 0.6, "maybe?"],
    ["ENGAGED_NOT_BUYING", 0.95, "this is so inspiring 🔥"],
    ["CRITICAL_NEGATIVE", 0.97, "scam, I want a refund"],
    ["UNCERTAIN", 0.5, "what lane will you be in?"],
    ["LOW_SIGNAL", 0.9, "same"],
    ["SPAM", 0.99, "follow 4 follow"],
    ["NOT_A_LEAD", 0.9, "happy birthday bro"],
    ["HIGH_INTENT", 0.95, "my results were botched and the side effects are awful, how do I sign up again?"],
  ];
  const SETUPS = [
    ["defaults", {}],
    ["post overrides", { monitoring: { actions_per_class: { ENGAGED_NOT_BUYING: "dm", CRITICAL_NEGATIVE: "dm" }, treatment_key: "strength" } }],
    ["open thread + webhook", { webhook: true, conversations: [{ id: "conv-1", user_id: "coach-1", instagram_sender_id: "lead-1", origin: "inbound", disclosed_at: null }] }],
  ];

  beforeEach(() => vi.clearAllMocks());

  it.each(SETUPS)("%s", async (_label, opts) => {
    const out = [];
    for (const [cls, confidence, text] of CASES) {
      setup(opts);
      classifyComment.mockResolvedValueOnce({ classification: { class: cls, confidence, signals: [] }, raw: {}, latencyMs: 1 });
      sendPrivateReplyToComment.mockClear();
      await handleCommentEvent(
        { id: IGBA },
        { field: "comments", value: { id: "c-1", text, media: { id: "media-1" }, from: { id: "lead-1", username: "jane" }, created_time: new Date().toISOString() } }
      );
      out.push({
        cls,
        confidence,
        text,
        sent: sendPrivateReplyToComment.mock.calls.map((c) => c.slice(1, 3)),
        log: strip(db.tables.comment_to_dm_log),
        conversations: strip(db.tables.conversations),
        messages: strip(db.tables.messages),
        lead_profiles: strip(db.tables.lead_profiles),
        events: strip(db.tables.outbound_webhook_events),
        emails: sendEmail.mock.calls.length,
      });
    }
    expect(out).toMatchSnapshot();
  });
});
